---
title: "DataAnalysis"
output: 
  html_document:
    keep_md: true
---

```{r}
library(tidyverse)
library(readr)
library(igraph)
```

# Load Data 
```{r}
Artists<-read.csv("~/Desktop/describing_your_data/wikipedia_api/Data_Sets/artandfemWiki.csv")
Athletes<- read.csv("~/Desktop/describing_your_data/wikipedia_api/Data_Sets/athletesWiki.csv")
Politicians <- read.csv("~/Desktop/describing_your_data/wikipedia_api/Data_Sets/politicsWiki.csv")
Scientists <- read.csv("~/Desktop/describing_your_data/wikipedia_api/Data_Sets/ScientistsWiki.csv")

# Add a column to each for their group 
Artists$type<-"Artists"
Artists<-subset(Artists, select =-X)
Athletes$type<-"Athletes"
Politicians$type <-"Politicians"
Scientists$type<-"Scientists"

# Combine into one data set 
all_data<- rbind(Artists,Athletes,Politicians,Scientists)
head(all_data)
head(Artists)

all_data_df<-as.data.frame(all_data)
head(all_data_df)
```

# Descriptive Statistics of each group: 

**Number of articles per group** 

```{r}
all_data_df %>%
  group_by(type) %>%
  summarise(articles=n_distinct(title))

```

**Average length of articles per group**
```{r}
all_data_df %>%
  group_by(type)%>%
  summarise(average=mean(length), median=median(length), max=max(length), min=min(length))

library(ggridges)
  
ggplot(all_data_df)+
  geom_density_ridges(aes(x=log(length), y=type, fill=type), quantile_lines=TRUE, quantiles=2, show.legend=FALSE)+ 
  ggtitle("Length of articles, by type")+ 
  ylab(" ")+
  xlab("log of character count")

```
**Average number of editors**
```{r}
editors<-all_data_df%>%
  group_by(type) %>%
  summarise(average=mean(editorcount), median=median(editorcount), max=max(editorcount), min=min(editorcount))
editors
```

**Average number of page views**
```{r}
pageviews<-all_data_df%>%
  group_by(type) %>%
  summarise(average=mean(aveviews), median=median(aveviews), max=max(aveviews), min=min(aveviews))

ggplot() +
  geom_point(data=pageviews, aes(x=type, y=median, col=type), shape=16, size=8, show.legend=FALSE)+
  theme_minimal()+
  xlab("")+
  ylab("Median Daily Page Views")

ggplot()+
  geom_point(data=editors, aes(x=type, y=median, col=type), shape=18, size=8, show.legend=FALSE)+
  theme_minimal()+
  xlab("")+
  ylab("Median Editors")

```

# Network Statistics (TBD)


ArtistsNet<-read.csv("~/Desktop/describing_your_data/wikipedia_api/Wikilinks_Networks/artistsNet.csv")
colnames(ArtistsNet)<-c('source','target')
head(ArtistsNet)

ArtistsNodes<- Artists$title
ArtistsNodes[duplicated(ArtistsNodes)]
ArtistsNetwork<- graph.data.frame(ArtistsNet,directed=F,vertices=NULL)
Anet1<-subgraph.edges(ArtistsNetwork, which(E(ArtistsNetwork)$weight > 1))
degree(ArtistsNetwork)
betweenness(ArtistsNetwork)
graph.density(ArtistsNetwork)

